services:
  - type: web
    name: laravel-app
    env: php
    buildCommand: "docker build -t laravel-app ."
    startCommand: "docker run -p 80:80 laravel-app"
    settings:
      documentRoot: "/var/www/html/public"
